version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports: 
      - 10.255.20.57:6379:6379/tcp
    network_mode: "bridge"
  mysql:
    image: mysql:5.7.26
    container_name: mysql
    ports:
      - 10.255.20.57:3306:3306/tcp
    network_mode: "bridge"
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
      - $PWD/sql_data:/var/lib/mysql
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 0.0.0.0:8080:8080/tcp
    network_mode: "bridge"
    volumes:
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/html:/usr/share/nginx/html
  java:
    image: java:8
    container_name: java
    ports:
      - 0.0.0.0:8088:8088/tcp
    network_mode: "bridge"
    links:
      - mysql
      - redis
    volumes:
      - $PWD/user_jar:/jar
      - $PWD/html-main/ca-web/resources/bvh:/root/8079
      - $PWD/html/ca-web/resources/bvh:/root/8080
    command: /usr/bin/java -jar /jar/user.jar
    depends_on:
      - mysql
      - redis
    restart: always
